apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook
  namespace: webapp
spec: 
  destination: 
    namespace: webapp
    server: "https://9551C1CEE4E6167C358EEF94B6E7BDB5.gr7.eu-west-1.eks.amazonaws.com"
  project: default
  source: 
    path: webapp
    repoURL: "https://github.com/sivasankardevops/kubernetes.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
